// Copyright NVIDIA Corporation 2018 - 2022
// TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THIS SOFTWARE IS PROVIDED
// *AS IS* AND NVIDIA AND ITS SUPPLIERS DISCLAIM ALL WARRANTIES, EITHER EXPRESS
// OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  IN NO EVENT SHALL
// NVIDIA OR ITS SUPPLIERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, OR
// CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR
// LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS
// INFORMATION, OR ANY OTHER PECUNIARY LOSS) ARISING OUT OF THE USE OF OR
// INABILITY TO USE THIS SOFTWARE, EVEN IF NVIDIA HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGES.

/// \file HidDeviceDefs.h
/// Defines the logical device IDs sent from the client to the server

#pragma once

/// Device IDs, range is uint8_t
typedef enum NvstHidDeviceId_t
{
    /// Special ID for unknown / invalid device ID.
    NVST_HID_DEV_INVALID = 0,
    /// Wacom Intuos Pro M pen/tablet device
    NVST_HID_DEV_INTUOS_PRO_M = 1,
    ///\{
    /// Sony DualSense 5 Controllers
    NVST_HID_DEV_DUALSENSE_A = 2,
    NVST_HID_DEV_DUALSENSE_B = 3,
    NVST_HID_DEV_DUALSENSE_C = 4,
    NVST_HID_DEV_DUALSENSE_D = 5,
    ///\}
    /// For range control
    NVST_HID_DEV_SIZE
} NvstHidDeviceId;

#define HID_VID_SONY 0x054c
#define HID_PID_DUALSENSE 0x0ce6
